// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: delivery/proto/3party/3party.proto

package openapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *TestingRequest) Reset() {
	*x = TestingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_proto_3party_3party_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestingRequest) ProtoMessage() {}

func (x *TestingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_3party_3party_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestingRequest.ProtoReflect.Descriptor instead.
func (*TestingRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_3party_3party_proto_rawDescGZIP(), []int{0}
}

func (x *TestingRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type TestingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *TestingResponse) Reset() {
	*x = TestingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_proto_3party_3party_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestingResponse) ProtoMessage() {}

func (x *TestingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_3party_3party_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestingResponse.ProtoReflect.Descriptor instead.
func (*TestingResponse) Descriptor() ([]byte, []int) {
	return file_delivery_proto_3party_3party_proto_rawDescGZIP(), []int{1}
}

func (x *TestingResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type VerificationSIKPRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	KtpNumber string `protobuf:"bytes,2,opt,name=ktpNumber,proto3" json:"ktpNumber,omitempty"`
}

func (x *VerificationSIKPRequest) Reset() {
	*x = VerificationSIKPRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_proto_3party_3party_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerificationSIKPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationSIKPRequest) ProtoMessage() {}

func (x *VerificationSIKPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_3party_3party_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationSIKPRequest.ProtoReflect.Descriptor instead.
func (*VerificationSIKPRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_3party_3party_proto_rawDescGZIP(), []int{2}
}

func (x *VerificationSIKPRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VerificationSIKPRequest) GetKtpNumber() string {
	if x != nil {
		return x.KtpNumber
	}
	return ""
}

type VerificationSIKPReponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status                    int64                      `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message                   string                     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	MessageLocal              string                     `protobuf:"bytes,3,opt,name=messageLocal,proto3" json:"messageLocal,omitempty"`
	EmbedDataVerificationSIKP *EmbedDataVerificationSIKP `protobuf:"bytes,4,opt,name=EmbedDataVerificationSIKP,proto3" json:"EmbedDataVerificationSIKP,omitempty"`
}

func (x *VerificationSIKPReponse) Reset() {
	*x = VerificationSIKPReponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_proto_3party_3party_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerificationSIKPReponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationSIKPReponse) ProtoMessage() {}

func (x *VerificationSIKPReponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_3party_3party_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationSIKPReponse.ProtoReflect.Descriptor instead.
func (*VerificationSIKPReponse) Descriptor() ([]byte, []int) {
	return file_delivery_proto_3party_3party_proto_rawDescGZIP(), []int{3}
}

func (x *VerificationSIKPReponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *VerificationSIKPReponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VerificationSIKPReponse) GetMessageLocal() string {
	if x != nil {
		return x.MessageLocal
	}
	return ""
}

func (x *VerificationSIKPReponse) GetEmbedDataVerificationSIKP() *EmbedDataVerificationSIKP {
	if x != nil {
		return x.EmbedDataVerificationSIKP
	}
	return nil
}

type EmbedDataVerificationSIKP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode           int64                 `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	StatusDescription    string                `protobuf:"bytes,2,opt,name=statusDescription,proto3" json:"statusDescription,omitempty"`
	DataVerificationSIKP *DataVerificationSIKP `protobuf:"bytes,3,opt,name=DataVerificationSIKP,proto3" json:"DataVerificationSIKP,omitempty"`
}

func (x *EmbedDataVerificationSIKP) Reset() {
	*x = EmbedDataVerificationSIKP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_proto_3party_3party_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmbedDataVerificationSIKP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedDataVerificationSIKP) ProtoMessage() {}

func (x *EmbedDataVerificationSIKP) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_3party_3party_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedDataVerificationSIKP.ProtoReflect.Descriptor instead.
func (*EmbedDataVerificationSIKP) Descriptor() ([]byte, []int) {
	return file_delivery_proto_3party_3party_proto_rawDescGZIP(), []int{4}
}

func (x *EmbedDataVerificationSIKP) GetStatusCode() int64 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *EmbedDataVerificationSIKP) GetStatusDescription() string {
	if x != nil {
		return x.StatusDescription
	}
	return ""
}

func (x *EmbedDataVerificationSIKP) GetDataVerificationSIKP() *DataVerificationSIKP {
	if x != nil {
		return x.DataVerificationSIKP
	}
	return nil
}

type DataVerificationSIKP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BankCode   string `protobuf:"bytes,1,opt,name=bankCode,proto3" json:"bankCode,omitempty"`
	UploadDate string `protobuf:"bytes,2,opt,name=uploadDate,proto3" json:"uploadDate,omitempty"`
}

func (x *DataVerificationSIKP) Reset() {
	*x = DataVerificationSIKP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_proto_3party_3party_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataVerificationSIKP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataVerificationSIKP) ProtoMessage() {}

func (x *DataVerificationSIKP) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_3party_3party_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataVerificationSIKP.ProtoReflect.Descriptor instead.
func (*DataVerificationSIKP) Descriptor() ([]byte, []int) {
	return file_delivery_proto_3party_3party_proto_rawDescGZIP(), []int{5}
}

func (x *DataVerificationSIKP) GetBankCode() string {
	if x != nil {
		return x.BankCode
	}
	return ""
}

func (x *DataVerificationSIKP) GetUploadDate() string {
	if x != nil {
		return x.UploadDate
	}
	return ""
}

type CheckPlafondSIKPRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	KtpNumber string `protobuf:"bytes,2,opt,name=ktpNumber,proto3" json:"ktpNumber,omitempty"`
}

func (x *CheckPlafondSIKPRequest) Reset() {
	*x = CheckPlafondSIKPRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_proto_3party_3party_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckPlafondSIKPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPlafondSIKPRequest) ProtoMessage() {}

func (x *CheckPlafondSIKPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_3party_3party_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPlafondSIKPRequest.ProtoReflect.Descriptor instead.
func (*CheckPlafondSIKPRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_3party_3party_proto_rawDescGZIP(), []int{6}
}

func (x *CheckPlafondSIKPRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckPlafondSIKPRequest) GetKtpNumber() string {
	if x != nil {
		return x.KtpNumber
	}
	return ""
}

type CheckPlafondSIKPReponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status                    int64                      `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message                   string                     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	MessageLocal              string                     `protobuf:"bytes,3,opt,name=messageLocal,proto3" json:"messageLocal,omitempty"`
	EmbedDataCheckPlafondSIKP *EmbedDataCheckPlafondSIKP `protobuf:"bytes,4,opt,name=EmbedDataCheckPlafondSIKP,proto3" json:"EmbedDataCheckPlafondSIKP,omitempty"`
}

func (x *CheckPlafondSIKPReponse) Reset() {
	*x = CheckPlafondSIKPReponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_proto_3party_3party_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckPlafondSIKPReponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPlafondSIKPReponse) ProtoMessage() {}

func (x *CheckPlafondSIKPReponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_3party_3party_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPlafondSIKPReponse.ProtoReflect.Descriptor instead.
func (*CheckPlafondSIKPReponse) Descriptor() ([]byte, []int) {
	return file_delivery_proto_3party_3party_proto_rawDescGZIP(), []int{7}
}

func (x *CheckPlafondSIKPReponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CheckPlafondSIKPReponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CheckPlafondSIKPReponse) GetMessageLocal() string {
	if x != nil {
		return x.MessageLocal
	}
	return ""
}

func (x *CheckPlafondSIKPReponse) GetEmbedDataCheckPlafondSIKP() *EmbedDataCheckPlafondSIKP {
	if x != nil {
		return x.EmbedDataCheckPlafondSIKP
	}
	return nil
}

type EmbedDataCheckPlafondSIKP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode           int64                   `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	StatusDescription    string                  `protobuf:"bytes,2,opt,name=statusDescription,proto3" json:"statusDescription,omitempty"`
	DataCheckPlafondSIKP []*DataCheckPlafondSIKP `protobuf:"bytes,3,rep,name=DataCheckPlafondSIKP,proto3" json:"DataCheckPlafondSIKP,omitempty"`
}

func (x *EmbedDataCheckPlafondSIKP) Reset() {
	*x = EmbedDataCheckPlafondSIKP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_proto_3party_3party_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmbedDataCheckPlafondSIKP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedDataCheckPlafondSIKP) ProtoMessage() {}

func (x *EmbedDataCheckPlafondSIKP) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_3party_3party_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedDataCheckPlafondSIKP.ProtoReflect.Descriptor instead.
func (*EmbedDataCheckPlafondSIKP) Descriptor() ([]byte, []int) {
	return file_delivery_proto_3party_3party_proto_rawDescGZIP(), []int{8}
}

func (x *EmbedDataCheckPlafondSIKP) GetStatusCode() int64 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *EmbedDataCheckPlafondSIKP) GetStatusDescription() string {
	if x != nil {
		return x.StatusDescription
	}
	return ""
}

func (x *EmbedDataCheckPlafondSIKP) GetDataCheckPlafondSIKP() []*DataCheckPlafondSIKP {
	if x != nil {
		return x.DataCheckPlafondSIKP
	}
	return nil
}

type DataCheckPlafondSIKP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KtpNumber          string `protobuf:"bytes,1,opt,name=ktpNumber,proto3" json:"ktpNumber,omitempty"`
	Scheme             int64  `protobuf:"varint,2,opt,name=scheme,proto3" json:"scheme,omitempty"`
	TotalLimitDefault  int64  `protobuf:"varint,3,opt,name=totalLimitDefault,proto3" json:"totalLimitDefault,omitempty"`
	TotalLimit         int64  `protobuf:"varint,4,opt,name=totalLimit,proto3" json:"totalLimit,omitempty"`
	LimitActiveDefault int64  `protobuf:"varint,5,opt,name=limitActiveDefault,proto3" json:"limitActiveDefault,omitempty"`
	LimitActive        int64  `protobuf:"varint,6,opt,name=limitActive,proto3" json:"limitActive,omitempty"`
	BankCode           int64  `protobuf:"varint,7,opt,name=bankCode,proto3" json:"bankCode,omitempty"`
}

func (x *DataCheckPlafondSIKP) Reset() {
	*x = DataCheckPlafondSIKP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_proto_3party_3party_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataCheckPlafondSIKP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataCheckPlafondSIKP) ProtoMessage() {}

func (x *DataCheckPlafondSIKP) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_3party_3party_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataCheckPlafondSIKP.ProtoReflect.Descriptor instead.
func (*DataCheckPlafondSIKP) Descriptor() ([]byte, []int) {
	return file_delivery_proto_3party_3party_proto_rawDescGZIP(), []int{9}
}

func (x *DataCheckPlafondSIKP) GetKtpNumber() string {
	if x != nil {
		return x.KtpNumber
	}
	return ""
}

func (x *DataCheckPlafondSIKP) GetScheme() int64 {
	if x != nil {
		return x.Scheme
	}
	return 0
}

func (x *DataCheckPlafondSIKP) GetTotalLimitDefault() int64 {
	if x != nil {
		return x.TotalLimitDefault
	}
	return 0
}

func (x *DataCheckPlafondSIKP) GetTotalLimit() int64 {
	if x != nil {
		return x.TotalLimit
	}
	return 0
}

func (x *DataCheckPlafondSIKP) GetLimitActiveDefault() int64 {
	if x != nil {
		return x.LimitActiveDefault
	}
	return 0
}

func (x *DataCheckPlafondSIKP) GetLimitActive() int64 {
	if x != nil {
		return x.LimitActive
	}
	return 0
}

func (x *DataCheckPlafondSIKP) GetBankCode() int64 {
	if x != nil {
		return x.BankCode
	}
	return 0
}

type VerificationSICDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	KtpNumber string `protobuf:"bytes,2,opt,name=ktpNumber,proto3" json:"ktpNumber,omitempty"`
}

func (x *VerificationSICDRequest) Reset() {
	*x = VerificationSICDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_proto_3party_3party_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerificationSICDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationSICDRequest) ProtoMessage() {}

func (x *VerificationSICDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_3party_3party_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationSICDRequest.ProtoReflect.Descriptor instead.
func (*VerificationSICDRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_3party_3party_proto_rawDescGZIP(), []int{10}
}

func (x *VerificationSICDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VerificationSICDRequest) GetKtpNumber() string {
	if x != nil {
		return x.KtpNumber
	}
	return ""
}

type VerificationSICDReponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status                    int64                      `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message                   string                     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	MessageLocal              string                     `protobuf:"bytes,3,opt,name=messageLocal,proto3" json:"messageLocal,omitempty"`
	EmbedDataVerificationSICD *EmbedDataVerificationSICD `protobuf:"bytes,4,opt,name=EmbedDataVerificationSICD,proto3" json:"EmbedDataVerificationSICD,omitempty"`
}

func (x *VerificationSICDReponse) Reset() {
	*x = VerificationSICDReponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_proto_3party_3party_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerificationSICDReponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationSICDReponse) ProtoMessage() {}

func (x *VerificationSICDReponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_3party_3party_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationSICDReponse.ProtoReflect.Descriptor instead.
func (*VerificationSICDReponse) Descriptor() ([]byte, []int) {
	return file_delivery_proto_3party_3party_proto_rawDescGZIP(), []int{11}
}

func (x *VerificationSICDReponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *VerificationSICDReponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VerificationSICDReponse) GetMessageLocal() string {
	if x != nil {
		return x.MessageLocal
	}
	return ""
}

func (x *VerificationSICDReponse) GetEmbedDataVerificationSICD() *EmbedDataVerificationSICD {
	if x != nil {
		return x.EmbedDataVerificationSICD
	}
	return nil
}

type EmbedDataVerificationSICD struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode           int64                   `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	StatusDescription    string                  `protobuf:"bytes,2,opt,name=statusDescription,proto3" json:"statusDescription,omitempty"`
	DataVerificationSICD []*DataVerificationSICD `protobuf:"bytes,3,rep,name=DataVerificationSICD,proto3" json:"DataVerificationSICD,omitempty"`
}

func (x *EmbedDataVerificationSICD) Reset() {
	*x = EmbedDataVerificationSICD{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_proto_3party_3party_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmbedDataVerificationSICD) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedDataVerificationSICD) ProtoMessage() {}

func (x *EmbedDataVerificationSICD) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_3party_3party_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedDataVerificationSICD.ProtoReflect.Descriptor instead.
func (*EmbedDataVerificationSICD) Descriptor() ([]byte, []int) {
	return file_delivery_proto_3party_3party_proto_rawDescGZIP(), []int{12}
}

func (x *EmbedDataVerificationSICD) GetStatusCode() int64 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *EmbedDataVerificationSICD) GetStatusDescription() string {
	if x != nil {
		return x.StatusDescription
	}
	return ""
}

func (x *EmbedDataVerificationSICD) GetDataVerificationSICD() []*DataVerificationSICD {
	if x != nil {
		return x.DataVerificationSICD
	}
	return nil
}

type DataVerificationSICD struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PrakarsaId int64  `protobuf:"varint,2,opt,name=prakarsaId,proto3" json:"prakarsaId,omitempty"`
	KtpNumber  string `protobuf:"bytes,3,opt,name=ktpNumber,proto3" json:"ktpNumber,omitempty"`
	Reason     string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	Status     int64  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt  string `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt  string `protobuf:"bytes,7,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
}

func (x *DataVerificationSICD) Reset() {
	*x = DataVerificationSICD{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_proto_3party_3party_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataVerificationSICD) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataVerificationSICD) ProtoMessage() {}

func (x *DataVerificationSICD) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_3party_3party_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataVerificationSICD.ProtoReflect.Descriptor instead.
func (*DataVerificationSICD) Descriptor() ([]byte, []int) {
	return file_delivery_proto_3party_3party_proto_rawDescGZIP(), []int{13}
}

func (x *DataVerificationSICD) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DataVerificationSICD) GetPrakarsaId() int64 {
	if x != nil {
		return x.PrakarsaId
	}
	return 0
}

func (x *DataVerificationSICD) GetKtpNumber() string {
	if x != nil {
		return x.KtpNumber
	}
	return ""
}

func (x *DataVerificationSICD) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *DataVerificationSICD) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DataVerificationSICD) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *DataVerificationSICD) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_delivery_proto_3party_3party_proto protoreflect.FileDescriptor

var file_delivery_proto_3party_3party_proto_rawDesc = []byte{
	0x0a, 0x22, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x33, 0x70, 0x61, 0x72, 0x74, 0x79, 0x2f, 0x33, 0x70, 0x61, 0x72, 0x74, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x24, 0x0a, 0x0e, 0x54,
	0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x22, 0x29, 0x0a, 0x0f, 0x54, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x4f, 0x0a, 0x17,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x49, 0x4b, 0x50,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x6b, 0x74, 0x70, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x6b, 0x74, 0x70, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0xcf, 0x01,
	0x0a, 0x17, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x49,
	0x4b, 0x50, 0x52, 0x65, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x12,
	0x5e, 0x0a, 0x19, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x49, 0x4b, 0x50, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x62, 0x65, 0x64,
	0x44, 0x61, 0x74, 0x61, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x49, 0x4b, 0x50, 0x52, 0x19, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x49, 0x4b, 0x50, 0x22,
	0xba, 0x01, 0x0a, 0x19, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x49, 0x4b, 0x50, 0x12, 0x1e, 0x0a,
	0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2c, 0x0a,
	0x11, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x4f, 0x0a, 0x14, 0x44,
	0x61, 0x74, 0x61, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x49, 0x4b, 0x50, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x49, 0x4b, 0x50, 0x52, 0x14, 0x44, 0x61, 0x74, 0x61, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x49, 0x4b, 0x50, 0x22, 0x52, 0x0a, 0x14,
	0x44, 0x61, 0x74, 0x61, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x49, 0x4b, 0x50, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x61, 0x6e, 0x6b, 0x43, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x61, 0x6e, 0x6b, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x44, 0x61, 0x74, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x44, 0x61, 0x74, 0x65,
	0x22, 0x4f, 0x0a, 0x17, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x6c, 0x61, 0x66, 0x6f, 0x6e, 0x64,
	0x53, 0x49, 0x4b, 0x50, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x6b, 0x74, 0x70, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6b, 0x74, 0x70, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x22, 0xcf, 0x01, 0x0a, 0x17, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x6c, 0x61, 0x66, 0x6f,
	0x6e, 0x64, 0x53, 0x49, 0x4b, 0x50, 0x52, 0x65, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x22, 0x0a, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4c, 0x6f,
	0x63, 0x61, 0x6c, 0x12, 0x5e, 0x0a, 0x19, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x6c, 0x61, 0x66, 0x6f, 0x6e, 0x64, 0x53, 0x49, 0x4b, 0x50,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45,
	0x6d, 0x62, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x6c, 0x61,
	0x66, 0x6f, 0x6e, 0x64, 0x53, 0x49, 0x4b, 0x50, 0x52, 0x19, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x44,
	0x61, 0x74, 0x61, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x6c, 0x61, 0x66, 0x6f, 0x6e, 0x64, 0x53,
	0x49, 0x4b, 0x50, 0x22, 0xba, 0x01, 0x0a, 0x19, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x44, 0x61, 0x74,
	0x61, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x6c, 0x61, 0x66, 0x6f, 0x6e, 0x64, 0x53, 0x49, 0x4b,
	0x50, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x2c, 0x0a, 0x11, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x44, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x4f, 0x0a, 0x14, 0x44, 0x61, 0x74, 0x61, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x6c, 0x61, 0x66,
	0x6f, 0x6e, 0x64, 0x53, 0x49, 0x4b, 0x50, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50,
	0x6c, 0x61, 0x66, 0x6f, 0x6e, 0x64, 0x53, 0x49, 0x4b, 0x50, 0x52, 0x14, 0x44, 0x61, 0x74, 0x61,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x6c, 0x61, 0x66, 0x6f, 0x6e, 0x64, 0x53, 0x49, 0x4b, 0x50,
	0x22, 0x88, 0x02, 0x0a, 0x14, 0x44, 0x61, 0x74, 0x61, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x6c,
	0x61, 0x66, 0x6f, 0x6e, 0x64, 0x53, 0x49, 0x4b, 0x50, 0x12, 0x1c, 0x0a, 0x09, 0x6b, 0x74, 0x70,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6b, 0x74,
	0x70, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x12,
	0x2c, 0x0a, 0x11, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x44, 0x65, 0x66,
	0x61, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x1e, 0x0a,
	0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x2e, 0x0a,
	0x12, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x44, 0x65, 0x66, 0x61,
	0x75, 0x6c, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x12, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x20, 0x0a,
	0x0b, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0b, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x62, 0x61, 0x6e, 0x6b, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x62, 0x61, 0x6e, 0x6b, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x4f, 0x0a, 0x17, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x49, 0x43, 0x44, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c,
	0x0a, 0x09, 0x6b, 0x74, 0x70, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x6b, 0x74, 0x70, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0xcf, 0x01, 0x0a,
	0x17, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x49, 0x43,
	0x44, 0x52, 0x65, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x12, 0x5e,
	0x0a, 0x19, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x49, 0x43, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x44,
	0x61, 0x74, 0x61, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x49, 0x43, 0x44, 0x52, 0x19, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x49, 0x43, 0x44, 0x22, 0xba,
	0x01, 0x0a, 0x19, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x49, 0x43, 0x44, 0x12, 0x1e, 0x0a, 0x0a,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2c, 0x0a, 0x11,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x44,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x4f, 0x0a, 0x14, 0x44, 0x61,
	0x74, 0x61, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x49,
	0x43, 0x44, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x49, 0x43, 0x44, 0x52, 0x14, 0x44, 0x61, 0x74, 0x61, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x49, 0x43, 0x44, 0x22, 0xd0, 0x01, 0x0a, 0x14,
	0x44, 0x61, 0x74, 0x61, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x49, 0x43, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x61, 0x6b, 0x61, 0x72, 0x73, 0x61,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x70, 0x72, 0x61, 0x6b, 0x61, 0x72,
	0x73, 0x61, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x6b, 0x74, 0x70, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6b, 0x74, 0x70, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x32, 0xc9,
	0x02, 0x0a, 0x11, 0x54, 0x68, 0x69, 0x72, 0x64, 0x50, 0x61, 0x72, 0x74, 0x79, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x07, 0x54, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x12,
	0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54,
	0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x52,
	0x0a, 0x10, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x49,
	0x4b, 0x50, 0x12, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x49, 0x4b, 0x50, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x49, 0x4b, 0x50, 0x52, 0x65, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x52, 0x0a, 0x10, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x6c, 0x61, 0x66, 0x6f,
	0x6e, 0x64, 0x53, 0x49, 0x4b, 0x50, 0x12, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x50, 0x6c, 0x61, 0x66, 0x6f, 0x6e, 0x64, 0x53, 0x49, 0x4b, 0x50, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x50, 0x6c, 0x61, 0x66, 0x6f, 0x6e, 0x64, 0x53, 0x49, 0x4b, 0x50, 0x52,
	0x65, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x52, 0x0a, 0x10, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x49, 0x43, 0x44, 0x12, 0x1e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x49, 0x43, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x49, 0x43, 0x44, 0x52, 0x65, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x16, 0x5a, 0x14, 0x33, 0x70,
	0x61, 0x72, 0x74, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x61,
	0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_delivery_proto_3party_3party_proto_rawDescOnce sync.Once
	file_delivery_proto_3party_3party_proto_rawDescData = file_delivery_proto_3party_3party_proto_rawDesc
)

func file_delivery_proto_3party_3party_proto_rawDescGZIP() []byte {
	file_delivery_proto_3party_3party_proto_rawDescOnce.Do(func() {
		file_delivery_proto_3party_3party_proto_rawDescData = protoimpl.X.CompressGZIP(file_delivery_proto_3party_3party_proto_rawDescData)
	})
	return file_delivery_proto_3party_3party_proto_rawDescData
}

var file_delivery_proto_3party_3party_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_delivery_proto_3party_3party_proto_goTypes = []interface{}{
	(*TestingRequest)(nil),            // 0: proto.TestingRequest
	(*TestingResponse)(nil),           // 1: proto.TestingResponse
	(*VerificationSIKPRequest)(nil),   // 2: proto.VerificationSIKPRequest
	(*VerificationSIKPReponse)(nil),   // 3: proto.VerificationSIKPReponse
	(*EmbedDataVerificationSIKP)(nil), // 4: proto.EmbedDataVerificationSIKP
	(*DataVerificationSIKP)(nil),      // 5: proto.DataVerificationSIKP
	(*CheckPlafondSIKPRequest)(nil),   // 6: proto.CheckPlafondSIKPRequest
	(*CheckPlafondSIKPReponse)(nil),   // 7: proto.CheckPlafondSIKPReponse
	(*EmbedDataCheckPlafondSIKP)(nil), // 8: proto.EmbedDataCheckPlafondSIKP
	(*DataCheckPlafondSIKP)(nil),      // 9: proto.DataCheckPlafondSIKP
	(*VerificationSICDRequest)(nil),   // 10: proto.VerificationSICDRequest
	(*VerificationSICDReponse)(nil),   // 11: proto.VerificationSICDReponse
	(*EmbedDataVerificationSICD)(nil), // 12: proto.EmbedDataVerificationSICD
	(*DataVerificationSICD)(nil),      // 13: proto.DataVerificationSICD
}
var file_delivery_proto_3party_3party_proto_depIdxs = []int32{
	4,  // 0: proto.VerificationSIKPReponse.EmbedDataVerificationSIKP:type_name -> proto.EmbedDataVerificationSIKP
	5,  // 1: proto.EmbedDataVerificationSIKP.DataVerificationSIKP:type_name -> proto.DataVerificationSIKP
	8,  // 2: proto.CheckPlafondSIKPReponse.EmbedDataCheckPlafondSIKP:type_name -> proto.EmbedDataCheckPlafondSIKP
	9,  // 3: proto.EmbedDataCheckPlafondSIKP.DataCheckPlafondSIKP:type_name -> proto.DataCheckPlafondSIKP
	12, // 4: proto.VerificationSICDReponse.EmbedDataVerificationSICD:type_name -> proto.EmbedDataVerificationSICD
	13, // 5: proto.EmbedDataVerificationSICD.DataVerificationSICD:type_name -> proto.DataVerificationSICD
	0,  // 6: proto.ThirdPartyService.Testing:input_type -> proto.TestingRequest
	2,  // 7: proto.ThirdPartyService.VerificationSIKP:input_type -> proto.VerificationSIKPRequest
	6,  // 8: proto.ThirdPartyService.CheckPlafondSIKP:input_type -> proto.CheckPlafondSIKPRequest
	10, // 9: proto.ThirdPartyService.VerificationSICD:input_type -> proto.VerificationSICDRequest
	1,  // 10: proto.ThirdPartyService.Testing:output_type -> proto.TestingResponse
	3,  // 11: proto.ThirdPartyService.VerificationSIKP:output_type -> proto.VerificationSIKPReponse
	7,  // 12: proto.ThirdPartyService.CheckPlafondSIKP:output_type -> proto.CheckPlafondSIKPReponse
	11, // 13: proto.ThirdPartyService.VerificationSICD:output_type -> proto.VerificationSICDReponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_delivery_proto_3party_3party_proto_init() }
func file_delivery_proto_3party_3party_proto_init() {
	if File_delivery_proto_3party_3party_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_delivery_proto_3party_3party_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_delivery_proto_3party_3party_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_delivery_proto_3party_3party_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerificationSIKPRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_delivery_proto_3party_3party_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerificationSIKPReponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_delivery_proto_3party_3party_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmbedDataVerificationSIKP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_delivery_proto_3party_3party_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataVerificationSIKP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_delivery_proto_3party_3party_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckPlafondSIKPRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_delivery_proto_3party_3party_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckPlafondSIKPReponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_delivery_proto_3party_3party_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmbedDataCheckPlafondSIKP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_delivery_proto_3party_3party_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataCheckPlafondSIKP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_delivery_proto_3party_3party_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerificationSICDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_delivery_proto_3party_3party_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerificationSICDReponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_delivery_proto_3party_3party_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmbedDataVerificationSICD); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_delivery_proto_3party_3party_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataVerificationSICD); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_delivery_proto_3party_3party_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_delivery_proto_3party_3party_proto_goTypes,
		DependencyIndexes: file_delivery_proto_3party_3party_proto_depIdxs,
		MessageInfos:      file_delivery_proto_3party_3party_proto_msgTypes,
	}.Build()
	File_delivery_proto_3party_3party_proto = out.File
	file_delivery_proto_3party_3party_proto_rawDesc = nil
	file_delivery_proto_3party_3party_proto_goTypes = nil
	file_delivery_proto_3party_3party_proto_depIdxs = nil
}
