// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: delivery/proto/3party/3party.proto

package openapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *TestingRequest) Reset() {
	*x = TestingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_proto_3party_3party_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestingRequest) ProtoMessage() {}

func (x *TestingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_3party_3party_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestingRequest.ProtoReflect.Descriptor instead.
func (*TestingRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_3party_3party_proto_rawDescGZIP(), []int{0}
}

func (x *TestingRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type TestingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *TestingResponse) Reset() {
	*x = TestingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_proto_3party_3party_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestingResponse) ProtoMessage() {}

func (x *TestingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_3party_3party_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestingResponse.ProtoReflect.Descriptor instead.
func (*TestingResponse) Descriptor() ([]byte, []int) {
	return file_delivery_proto_3party_3party_proto_rawDescGZIP(), []int{1}
}

func (x *TestingResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type VerificationSIKPRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	KtpNumber string `protobuf:"bytes,2,opt,name=ktpNumber,proto3" json:"ktpNumber,omitempty"`
}

func (x *VerificationSIKPRequest) Reset() {
	*x = VerificationSIKPRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_proto_3party_3party_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerificationSIKPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationSIKPRequest) ProtoMessage() {}

func (x *VerificationSIKPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_3party_3party_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationSIKPRequest.ProtoReflect.Descriptor instead.
func (*VerificationSIKPRequest) Descriptor() ([]byte, []int) {
	return file_delivery_proto_3party_3party_proto_rawDescGZIP(), []int{2}
}

func (x *VerificationSIKPRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VerificationSIKPRequest) GetKtpNumber() string {
	if x != nil {
		return x.KtpNumber
	}
	return ""
}

type VerificationSIKPReponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status                    int64                      `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message                   string                     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	MessageLocal              string                     `protobuf:"bytes,3,opt,name=messageLocal,proto3" json:"messageLocal,omitempty"`
	EmbedDataVerificationSIKP *EmbedDataVerificationSIKP `protobuf:"bytes,4,opt,name=EmbedDataVerificationSIKP,proto3" json:"EmbedDataVerificationSIKP,omitempty"`
}

func (x *VerificationSIKPReponse) Reset() {
	*x = VerificationSIKPReponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_proto_3party_3party_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerificationSIKPReponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationSIKPReponse) ProtoMessage() {}

func (x *VerificationSIKPReponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_3party_3party_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationSIKPReponse.ProtoReflect.Descriptor instead.
func (*VerificationSIKPReponse) Descriptor() ([]byte, []int) {
	return file_delivery_proto_3party_3party_proto_rawDescGZIP(), []int{3}
}

func (x *VerificationSIKPReponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *VerificationSIKPReponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VerificationSIKPReponse) GetMessageLocal() string {
	if x != nil {
		return x.MessageLocal
	}
	return ""
}

func (x *VerificationSIKPReponse) GetEmbedDataVerificationSIKP() *EmbedDataVerificationSIKP {
	if x != nil {
		return x.EmbedDataVerificationSIKP
	}
	return nil
}

type EmbedDataVerificationSIKP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode        int64     `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	StatusDescription string    `protobuf:"bytes,2,opt,name=statusDescription,proto3" json:"statusDescription,omitempty"`
	DataSIKP          *DataSIKP `protobuf:"bytes,3,opt,name=dataSIKP,proto3" json:"dataSIKP,omitempty"`
}

func (x *EmbedDataVerificationSIKP) Reset() {
	*x = EmbedDataVerificationSIKP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_proto_3party_3party_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmbedDataVerificationSIKP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedDataVerificationSIKP) ProtoMessage() {}

func (x *EmbedDataVerificationSIKP) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_3party_3party_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedDataVerificationSIKP.ProtoReflect.Descriptor instead.
func (*EmbedDataVerificationSIKP) Descriptor() ([]byte, []int) {
	return file_delivery_proto_3party_3party_proto_rawDescGZIP(), []int{4}
}

func (x *EmbedDataVerificationSIKP) GetStatusCode() int64 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *EmbedDataVerificationSIKP) GetStatusDescription() string {
	if x != nil {
		return x.StatusDescription
	}
	return ""
}

func (x *EmbedDataVerificationSIKP) GetDataSIKP() *DataSIKP {
	if x != nil {
		return x.DataSIKP
	}
	return nil
}

type DataSIKP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BankCode   string `protobuf:"bytes,1,opt,name=bankCode,proto3" json:"bankCode,omitempty"`
	UploadDate string `protobuf:"bytes,2,opt,name=uploadDate,proto3" json:"uploadDate,omitempty"`
}

func (x *DataSIKP) Reset() {
	*x = DataSIKP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_proto_3party_3party_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataSIKP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataSIKP) ProtoMessage() {}

func (x *DataSIKP) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_proto_3party_3party_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataSIKP.ProtoReflect.Descriptor instead.
func (*DataSIKP) Descriptor() ([]byte, []int) {
	return file_delivery_proto_3party_3party_proto_rawDescGZIP(), []int{5}
}

func (x *DataSIKP) GetBankCode() string {
	if x != nil {
		return x.BankCode
	}
	return ""
}

func (x *DataSIKP) GetUploadDate() string {
	if x != nil {
		return x.UploadDate
	}
	return ""
}

var File_delivery_proto_3party_3party_proto protoreflect.FileDescriptor

var file_delivery_proto_3party_3party_proto_rawDesc = []byte{
	0x0a, 0x22, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x33, 0x70, 0x61, 0x72, 0x74, 0x79, 0x2f, 0x33, 0x70, 0x61, 0x72, 0x74, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x24, 0x0a, 0x0e, 0x54,
	0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x22, 0x29, 0x0a, 0x0f, 0x54, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x4f, 0x0a, 0x17,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x49, 0x4b, 0x50,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x6b, 0x74, 0x70, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x6b, 0x74, 0x70, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0xcf, 0x01,
	0x0a, 0x17, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x49,
	0x4b, 0x50, 0x52, 0x65, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x12,
	0x5e, 0x0a, 0x19, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x49, 0x4b, 0x50, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x62, 0x65, 0x64,
	0x44, 0x61, 0x74, 0x61, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x49, 0x4b, 0x50, 0x52, 0x19, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x49, 0x4b, 0x50, 0x22,
	0x96, 0x01, 0x0a, 0x19, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x49, 0x4b, 0x50, 0x12, 0x1e, 0x0a,
	0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2c, 0x0a,
	0x11, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2b, 0x0a, 0x08, 0x64,
	0x61, 0x74, 0x61, 0x53, 0x49, 0x4b, 0x50, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x53, 0x49, 0x4b, 0x50, 0x52, 0x08,
	0x64, 0x61, 0x74, 0x61, 0x53, 0x49, 0x4b, 0x50, 0x22, 0x46, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61,
	0x53, 0x49, 0x4b, 0x50, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x61, 0x6e, 0x6b, 0x43, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x61, 0x6e, 0x6b, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x44, 0x61, 0x74, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x44, 0x61, 0x74, 0x65,
	0x32, 0xa1, 0x01, 0x0a, 0x11, 0x54, 0x68, 0x69, 0x72, 0x64, 0x50, 0x61, 0x72, 0x74, 0x79, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x07, 0x54, 0x65, 0x73, 0x74, 0x69, 0x6e,
	0x67, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x54, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x52, 0x0a, 0x10, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x49, 0x4b, 0x50, 0x12, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x49, 0x4b, 0x50, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x49, 0x4b, 0x50, 0x52, 0x65, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x16, 0x5a, 0x14, 0x33, 0x70, 0x61, 0x72, 0x74, 0x79, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_delivery_proto_3party_3party_proto_rawDescOnce sync.Once
	file_delivery_proto_3party_3party_proto_rawDescData = file_delivery_proto_3party_3party_proto_rawDesc
)

func file_delivery_proto_3party_3party_proto_rawDescGZIP() []byte {
	file_delivery_proto_3party_3party_proto_rawDescOnce.Do(func() {
		file_delivery_proto_3party_3party_proto_rawDescData = protoimpl.X.CompressGZIP(file_delivery_proto_3party_3party_proto_rawDescData)
	})
	return file_delivery_proto_3party_3party_proto_rawDescData
}

var file_delivery_proto_3party_3party_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_delivery_proto_3party_3party_proto_goTypes = []interface{}{
	(*TestingRequest)(nil),            // 0: proto.TestingRequest
	(*TestingResponse)(nil),           // 1: proto.TestingResponse
	(*VerificationSIKPRequest)(nil),   // 2: proto.VerificationSIKPRequest
	(*VerificationSIKPReponse)(nil),   // 3: proto.VerificationSIKPReponse
	(*EmbedDataVerificationSIKP)(nil), // 4: proto.EmbedDataVerificationSIKP
	(*DataSIKP)(nil),                  // 5: proto.dataSIKP
}
var file_delivery_proto_3party_3party_proto_depIdxs = []int32{
	4, // 0: proto.VerificationSIKPReponse.EmbedDataVerificationSIKP:type_name -> proto.EmbedDataVerificationSIKP
	5, // 1: proto.EmbedDataVerificationSIKP.dataSIKP:type_name -> proto.dataSIKP
	0, // 2: proto.ThirdPartyService.Testing:input_type -> proto.TestingRequest
	2, // 3: proto.ThirdPartyService.VerificationSIKP:input_type -> proto.VerificationSIKPRequest
	1, // 4: proto.ThirdPartyService.Testing:output_type -> proto.TestingResponse
	3, // 5: proto.ThirdPartyService.VerificationSIKP:output_type -> proto.VerificationSIKPReponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_delivery_proto_3party_3party_proto_init() }
func file_delivery_proto_3party_3party_proto_init() {
	if File_delivery_proto_3party_3party_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_delivery_proto_3party_3party_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_delivery_proto_3party_3party_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_delivery_proto_3party_3party_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerificationSIKPRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_delivery_proto_3party_3party_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerificationSIKPReponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_delivery_proto_3party_3party_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmbedDataVerificationSIKP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_delivery_proto_3party_3party_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataSIKP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_delivery_proto_3party_3party_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_delivery_proto_3party_3party_proto_goTypes,
		DependencyIndexes: file_delivery_proto_3party_3party_proto_depIdxs,
		MessageInfos:      file_delivery_proto_3party_3party_proto_msgTypes,
	}.Build()
	File_delivery_proto_3party_3party_proto = out.File
	file_delivery_proto_3party_3party_proto_rawDesc = nil
	file_delivery_proto_3party_3party_proto_goTypes = nil
	file_delivery_proto_3party_3party_proto_depIdxs = nil
}
